/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  ForwardReinvest,
  ForwardReinvestInterface,
} from "../../../contracts/modules/ForwardReinvest";

const _abi = [
  {
    inputs: [],
    name: "STRATEGY_NAME",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x61010961003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80636edd5446146038575b600080fd5b60736040518060400160405280601581526020017f466f7277617264205265696e766573742056302e32000000000000000000000081525081565b604051607e91906087565b60405180910390f35b600060208083528351808285015260005b8181101560b2578581018301518582016040015282016098565b506000604082860101526040601f19601f830116850101925050509291505056fea264697066735822122061b6fa5da76dd9d25ecc1cc1fad7ff7040e2b5e94e6aa532ea67ab826ffcac2a64736f6c63430008140033";

type ForwardReinvestConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ForwardReinvestConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ForwardReinvest__factory extends ContractFactory {
  constructor(...args: ForwardReinvestConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ForwardReinvest & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ForwardReinvest__factory {
    return super.connect(runner) as ForwardReinvest__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ForwardReinvestInterface {
    return new Interface(_abi) as ForwardReinvestInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ForwardReinvest {
    return new Contract(address, _abi, runner) as unknown as ForwardReinvest;
  }
}
