/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Swap,
  SwapInterface,
} from "../../../../contracts/utils/swap.sol/Swap";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "baseToken_",
        type: "address",
      },
      {
        internalType: "address",
        name: "targetToken_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_",
        type: "uint256",
      },
    ],
    name: "SWAP",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "SWAP_ROUTER",
    outputs: [
      {
        internalType: "contract ISwapRouter02",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Swap__factory {
  static readonly abi = _abi;
  static createInterface(): SwapInterface {
    return new Interface(_abi) as SwapInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Swap {
    return new Contract(address, _abi, runner) as unknown as Swap;
  }
}
