/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDCADataStructures {
  export type TokeDataStruct = {
    tokenAddress: AddressLike;
    decimals: BigNumberish;
    ticker: string;
  };

  export type TokeDataStructOutput = [
    tokenAddress: string,
    decimals: bigint,
    ticker: string
  ] & { tokenAddress: string; decimals: bigint; ticker: string };

  export type StrategyStruct = {
    accountAddress: AddressLike;
    baseToken: IDCADataStructures.TokeDataStruct;
    targetToken: IDCADataStructures.TokeDataStruct;
    interval: BigNumberish;
    amount: BigNumberish;
    strategyId: BigNumberish;
    active: boolean;
    reinvest: DCAReinvest.ReinvestStruct;
  };

  export type StrategyStructOutput = [
    accountAddress: string,
    baseToken: IDCADataStructures.TokeDataStructOutput,
    targetToken: IDCADataStructures.TokeDataStructOutput,
    interval: bigint,
    amount: bigint,
    strategyId: bigint,
    active: boolean,
    reinvest: DCAReinvest.ReinvestStructOutput
  ] & {
    accountAddress: string;
    baseToken: IDCADataStructures.TokeDataStructOutput;
    targetToken: IDCADataStructures.TokeDataStructOutput;
    interval: bigint;
    amount: bigint;
    strategyId: bigint;
    active: boolean;
    reinvest: DCAReinvest.ReinvestStructOutput;
  };
}

export declare namespace DCAReinvest {
  export type ReinvestStruct = {
    reinvestData: BytesLike;
    active: boolean;
    investCode: BigNumberish;
    dcaAccountAddress: AddressLike;
  };

  export type ReinvestStructOutput = [
    reinvestData: string,
    active: boolean,
    investCode: bigint,
    dcaAccountAddress: string
  ] & {
    reinvestData: string;
    active: boolean;
    investCode: bigint;
    dcaAccountAddress: string;
  };
}

export interface IDCAAccountInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "Execute"
      | "ExecutorDeactivateStrategy"
      | "FundAccount"
      | "SetupStrategy"
      | "SubscribeStrategy"
      | "UnFundAccount"
      | "UnsubscribeStrategy"
      | "WithdrawSavings"
      | "getBaseBalance"
      | "getTargetBalance"
      | "setStrategyReinvest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DCAReinvestLibraryChanged"
      | "NewStrategyCreated"
      | "StrategyExecuted"
      | "StrategyReinvestExecuted"
      | "StrategySubscribed"
      | "StrategyUnsubscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "Execute",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ExecutorDeactivateStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "FundAccount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SetupStrategy",
    values: [IDCADataStructures.StrategyStruct, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "SubscribeStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "UnFundAccount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "UnsubscribeStrategy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "WithdrawSavings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBaseBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTargetBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStrategyReinvest",
    values: [BigNumberish, DCAReinvest.ReinvestStruct]
  ): string;

  decodeFunctionResult(functionFragment: "Execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ExecutorDeactivateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FundAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SetupStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SubscribeStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UnFundAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UnsubscribeStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WithdrawSavings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBaseBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTargetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStrategyReinvest",
    data: BytesLike
  ): Result;
}

export namespace DCAReinvestLibraryChangedEvent {
  export type InputTuple = [newLibraryAddress: AddressLike];
  export type OutputTuple = [newLibraryAddress: string];
  export interface OutputObject {
    newLibraryAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewStrategyCreatedEvent {
  export type InputTuple = [strategyId_: BigNumberish];
  export type OutputTuple = [strategyId_: bigint];
  export interface OutputObject {
    strategyId_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyExecutedEvent {
  export type InputTuple = [
    strategyId_: BigNumberish,
    amountIn_: BigNumberish,
    reInvest_: boolean
  ];
  export type OutputTuple = [
    strategyId_: bigint,
    amountIn_: bigint,
    reInvest_: boolean
  ];
  export interface OutputObject {
    strategyId_: bigint;
    amountIn_: bigint;
    reInvest_: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyReinvestExecutedEvent {
  export type InputTuple = [strategyId_: BigNumberish, success: boolean];
  export type OutputTuple = [strategyId_: bigint, success: boolean];
  export interface OutputObject {
    strategyId_: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategySubscribedEvent {
  export type InputTuple = [strategyId_: BigNumberish, executor_: AddressLike];
  export type OutputTuple = [strategyId_: bigint, executor_: string];
  export interface OutputObject {
    strategyId_: bigint;
    executor_: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyUnsubscribedEvent {
  export type InputTuple = [strategyId_: BigNumberish];
  export type OutputTuple = [strategyId_: bigint];
  export interface OutputObject {
    strategyId_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDCAAccount extends BaseContract {
  connect(runner?: ContractRunner | null): IDCAAccount;
  waitForDeployment(): Promise<this>;

  interface: IDCAAccountInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  Execute: TypedContractMethod<
    [strategyId_: BigNumberish, feeAmount_: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  ExecutorDeactivateStrategy: TypedContractMethod<
    [strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  FundAccount: TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;

  SetupStrategy: TypedContractMethod<
    [
      newStrategy_: IDCADataStructures.StrategyStruct,
      seedFunds_: BigNumberish,
      subscribeToExecutor_: boolean
    ],
    [void],
    "nonpayable"
  >;

  SubscribeStrategy: TypedContractMethod<
    [strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  UnFundAccount: TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;

  UnsubscribeStrategy: TypedContractMethod<
    [strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  WithdrawSavings: TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBaseBalance: TypedContractMethod<
    [token_: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getTargetBalance: TypedContractMethod<
    [token_: AddressLike],
    [bigint],
    "nonpayable"
  >;

  setStrategyReinvest: TypedContractMethod<
    [strategyId_: BigNumberish, reinvest_: DCAReinvest.ReinvestStruct],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "Execute"
  ): TypedContractMethod<
    [strategyId_: BigNumberish, feeAmount_: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ExecutorDeactivateStrategy"
  ): TypedContractMethod<[strategyId_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "FundAccount"
  ): TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "SetupStrategy"
  ): TypedContractMethod<
    [
      newStrategy_: IDCADataStructures.StrategyStruct,
      seedFunds_: BigNumberish,
      subscribeToExecutor_: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "SubscribeStrategy"
  ): TypedContractMethod<[strategyId_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "UnFundAccount"
  ): TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "UnsubscribeStrategy"
  ): TypedContractMethod<[strategyId_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "WithdrawSavings"
  ): TypedContractMethod<
    [token_: AddressLike, amount_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBaseBalance"
  ): TypedContractMethod<[token_: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getTargetBalance"
  ): TypedContractMethod<[token_: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setStrategyReinvest"
  ): TypedContractMethod<
    [strategyId_: BigNumberish, reinvest_: DCAReinvest.ReinvestStruct],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DCAReinvestLibraryChanged"
  ): TypedContractEvent<
    DCAReinvestLibraryChangedEvent.InputTuple,
    DCAReinvestLibraryChangedEvent.OutputTuple,
    DCAReinvestLibraryChangedEvent.OutputObject
  >;
  getEvent(
    key: "NewStrategyCreated"
  ): TypedContractEvent<
    NewStrategyCreatedEvent.InputTuple,
    NewStrategyCreatedEvent.OutputTuple,
    NewStrategyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyExecuted"
  ): TypedContractEvent<
    StrategyExecutedEvent.InputTuple,
    StrategyExecutedEvent.OutputTuple,
    StrategyExecutedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyReinvestExecuted"
  ): TypedContractEvent<
    StrategyReinvestExecutedEvent.InputTuple,
    StrategyReinvestExecutedEvent.OutputTuple,
    StrategyReinvestExecutedEvent.OutputObject
  >;
  getEvent(
    key: "StrategySubscribed"
  ): TypedContractEvent<
    StrategySubscribedEvent.InputTuple,
    StrategySubscribedEvent.OutputTuple,
    StrategySubscribedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyUnsubscribed"
  ): TypedContractEvent<
    StrategyUnsubscribedEvent.InputTuple,
    StrategyUnsubscribedEvent.OutputTuple,
    StrategyUnsubscribedEvent.OutputObject
  >;

  filters: {
    "DCAReinvestLibraryChanged(address)": TypedContractEvent<
      DCAReinvestLibraryChangedEvent.InputTuple,
      DCAReinvestLibraryChangedEvent.OutputTuple,
      DCAReinvestLibraryChangedEvent.OutputObject
    >;
    DCAReinvestLibraryChanged: TypedContractEvent<
      DCAReinvestLibraryChangedEvent.InputTuple,
      DCAReinvestLibraryChangedEvent.OutputTuple,
      DCAReinvestLibraryChangedEvent.OutputObject
    >;

    "NewStrategyCreated(uint256)": TypedContractEvent<
      NewStrategyCreatedEvent.InputTuple,
      NewStrategyCreatedEvent.OutputTuple,
      NewStrategyCreatedEvent.OutputObject
    >;
    NewStrategyCreated: TypedContractEvent<
      NewStrategyCreatedEvent.InputTuple,
      NewStrategyCreatedEvent.OutputTuple,
      NewStrategyCreatedEvent.OutputObject
    >;

    "StrategyExecuted(uint256,uint256,bool)": TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;
    StrategyExecuted: TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;

    "StrategyReinvestExecuted(uint256,bool)": TypedContractEvent<
      StrategyReinvestExecutedEvent.InputTuple,
      StrategyReinvestExecutedEvent.OutputTuple,
      StrategyReinvestExecutedEvent.OutputObject
    >;
    StrategyReinvestExecuted: TypedContractEvent<
      StrategyReinvestExecutedEvent.InputTuple,
      StrategyReinvestExecutedEvent.OutputTuple,
      StrategyReinvestExecutedEvent.OutputObject
    >;

    "StrategySubscribed(uint256,address)": TypedContractEvent<
      StrategySubscribedEvent.InputTuple,
      StrategySubscribedEvent.OutputTuple,
      StrategySubscribedEvent.OutputObject
    >;
    StrategySubscribed: TypedContractEvent<
      StrategySubscribedEvent.InputTuple,
      StrategySubscribedEvent.OutputTuple,
      StrategySubscribedEvent.OutputObject
    >;

    "StrategyUnsubscribed(uint256)": TypedContractEvent<
      StrategyUnsubscribedEvent.InputTuple,
      StrategyUnsubscribedEvent.OutputTuple,
      StrategyUnsubscribedEvent.OutputObject
    >;
    StrategyUnsubscribed: TypedContractEvent<
      StrategyUnsubscribedEvent.InputTuple,
      StrategyUnsubscribedEvent.OutputTuple,
      StrategyUnsubscribedEvent.OutputObject
    >;
  };
}
