/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IDCADataStructures {
  export type FeeDistributionStruct = {
    amountToExecutor: BigNumberish;
    amountToComputing: BigNumberish;
    amountToAdmin: BigNumberish;
    feeAmount: BigNumberish;
    executionAddress: AddressLike;
    computingAddress: AddressLike;
    adminAddress: AddressLike;
  };

  export type FeeDistributionStructOutput = [
    amountToExecutor: bigint,
    amountToComputing: bigint,
    amountToAdmin: bigint,
    feeAmount: bigint,
    executionAddress: string,
    computingAddress: string,
    adminAddress: string
  ] & {
    amountToExecutor: bigint;
    amountToComputing: bigint;
    amountToAdmin: bigint;
    feeAmount: bigint;
    executionAddress: string;
    computingAddress: string;
    adminAddress: string;
  };

  export type TokeDataStruct = {
    tokenAddress: AddressLike;
    decimals: BigNumberish;
    ticker: string;
  };

  export type TokeDataStructOutput = [
    tokenAddress: string,
    decimals: bigint,
    ticker: string
  ] & { tokenAddress: string; decimals: bigint; ticker: string };

  export type StrategyStruct = {
    accountAddress: AddressLike;
    baseToken: IDCADataStructures.TokeDataStruct;
    targetToken: IDCADataStructures.TokeDataStruct;
    interval: BigNumberish;
    amount: BigNumberish;
    strategyId: BigNumberish;
    active: boolean;
    reinvest: DCAReinvest.ReinvestStruct;
  };

  export type StrategyStructOutput = [
    accountAddress: string,
    baseToken: IDCADataStructures.TokeDataStructOutput,
    targetToken: IDCADataStructures.TokeDataStructOutput,
    interval: bigint,
    amount: bigint,
    strategyId: bigint,
    active: boolean,
    reinvest: DCAReinvest.ReinvestStructOutput
  ] & {
    accountAddress: string;
    baseToken: IDCADataStructures.TokeDataStructOutput;
    targetToken: IDCADataStructures.TokeDataStructOutput;
    interval: bigint;
    amount: bigint;
    strategyId: bigint;
    active: boolean;
    reinvest: DCAReinvest.ReinvestStructOutput;
  };
}

export declare namespace DCAReinvest {
  export type ReinvestStruct = {
    active: boolean;
    investCode: BigNumberish;
    depositReinvestMethod: BytesLike;
    withdrawReinvestMethod: BytesLike;
    reinvestSpender: AddressLike;
  };

  export type ReinvestStructOutput = [
    active: boolean,
    investCode: bigint,
    depositReinvestMethod: string,
    withdrawReinvestMethod: string,
    reinvestSpender: string
  ] & {
    active: boolean;
    investCode: bigint;
    depositReinvestMethod: string;
    withdrawReinvestMethod: string;
    reinvestSpender: string;
  };
}

export interface DCAExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DistributeFees"
      | "Execute"
      | "ExecuteBatch"
      | "ForceUnsubscribe"
      | "Subscribe"
      | "Unsubscribe"
      | "addAdmin"
      | "changeExecutor"
      | "checkIfAdmin"
      | "getExecutorAddress"
      | "getSpecificStrategy"
      | "getTotalActiveStrategys"
      | "getTotalExecutions"
      | "owner"
      | "removeAdmin"
      | "removeExecutor"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DCAAccountSubscription"
      | "ExecutedDCA"
      | "ExecutionEOAAddressChange"
      | "FeesDistributed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DistributeFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "Execute",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ExecuteBatch",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "ForceUnsubscribe",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "Subscribe",
    values: [IDCADataStructures.StrategyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "Unsubscribe",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIfAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpecificStrategy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalActiveStrategys",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalExecutions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DistributeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ExecuteBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ForceUnsubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "Subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "Unsubscribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIfAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpecificStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalActiveStrategys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalExecutions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DCAAccountSubscriptionEvent {
  export type InputTuple = [
    DCAAccountAddress_: AddressLike,
    strategyId_: BigNumberish,
    strategyInterval_: BigNumberish,
    active_: boolean
  ];
  export type OutputTuple = [
    DCAAccountAddress_: string,
    strategyId_: bigint,
    strategyInterval_: bigint,
    active_: boolean
  ];
  export interface OutputObject {
    DCAAccountAddress_: string;
    strategyId_: bigint;
    strategyInterval_: bigint;
    active_: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedDCAEvent {
  export type InputTuple = [account_: AddressLike, strategyId_: BigNumberish];
  export type OutputTuple = [account_: string, strategyId_: bigint];
  export interface OutputObject {
    account_: string;
    strategyId_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionEOAAddressChangeEvent {
  export type InputTuple = [
    newExecutionEOA_: AddressLike,
    changer_: AddressLike
  ];
  export type OutputTuple = [newExecutionEOA_: string, changer_: string];
  export interface OutputObject {
    newExecutionEOA_: string;
    changer_: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesDistributedEvent {
  export type InputTuple = [token_: AddressLike, amount_: BigNumberish];
  export type OutputTuple = [token_: string, amount_: bigint];
  export interface OutputObject {
    token_: string;
    amount_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DCAExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): DCAExecutor;
  waitForDeployment(): Promise<this>;

  interface: DCAExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DistributeFees: TypedContractMethod<
    [tokenAddress_: AddressLike],
    [void],
    "nonpayable"
  >;

  Execute: TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  ExecuteBatch: TypedContractMethod<
    [DCAAccount_: AddressLike[], strategyId_: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  ForceUnsubscribe: TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  Subscribe: TypedContractMethod<
    [strategy_: IDCADataStructures.StrategyStruct],
    [void],
    "nonpayable"
  >;

  Unsubscribe: TypedContractMethod<
    [DCAAccountAddress_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;

  addAdmin: TypedContractMethod<[newAdmin_: AddressLike], [void], "nonpayable">;

  changeExecutor: TypedContractMethod<
    [newExecutorAddress_: AddressLike],
    [void],
    "nonpayable"
  >;

  checkIfAdmin: TypedContractMethod<
    [addressToCheck_: AddressLike],
    [boolean],
    "view"
  >;

  getExecutorAddress: TypedContractMethod<[], [string], "view">;

  getSpecificStrategy: TypedContractMethod<
    [dcaAccountAddress_: AddressLike, accountStrategyId_: BigNumberish],
    [IDCADataStructures.StrategyStructOutput],
    "view"
  >;

  getTotalActiveStrategys: TypedContractMethod<[], [bigint], "view">;

  getTotalExecutions: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeAdmin: TypedContractMethod<
    [oldAdmin_: AddressLike],
    [void],
    "nonpayable"
  >;

  removeExecutor: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DistributeFees"
  ): TypedContractMethod<[tokenAddress_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "Execute"
  ): TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ExecuteBatch"
  ): TypedContractMethod<
    [DCAAccount_: AddressLike[], strategyId_: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ForceUnsubscribe"
  ): TypedContractMethod<
    [DCAAccount_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "Subscribe"
  ): TypedContractMethod<
    [strategy_: IDCADataStructures.StrategyStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "Unsubscribe"
  ): TypedContractMethod<
    [DCAAccountAddress_: AddressLike, strategyId_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[newAdmin_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "changeExecutor"
  ): TypedContractMethod<
    [newExecutorAddress_: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkIfAdmin"
  ): TypedContractMethod<[addressToCheck_: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getExecutorAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSpecificStrategy"
  ): TypedContractMethod<
    [dcaAccountAddress_: AddressLike, accountStrategyId_: BigNumberish],
    [IDCADataStructures.StrategyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalActiveStrategys"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalExecutions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[oldAdmin_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeExecutor"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DCAAccountSubscription"
  ): TypedContractEvent<
    DCAAccountSubscriptionEvent.InputTuple,
    DCAAccountSubscriptionEvent.OutputTuple,
    DCAAccountSubscriptionEvent.OutputObject
  >;
  getEvent(
    key: "ExecutedDCA"
  ): TypedContractEvent<
    ExecutedDCAEvent.InputTuple,
    ExecutedDCAEvent.OutputTuple,
    ExecutedDCAEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionEOAAddressChange"
  ): TypedContractEvent<
    ExecutionEOAAddressChangeEvent.InputTuple,
    ExecutionEOAAddressChangeEvent.OutputTuple,
    ExecutionEOAAddressChangeEvent.OutputObject
  >;
  getEvent(
    key: "FeesDistributed"
  ): TypedContractEvent<
    FeesDistributedEvent.InputTuple,
    FeesDistributedEvent.OutputTuple,
    FeesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "DCAAccountSubscription(address,uint256,uint8,bool)": TypedContractEvent<
      DCAAccountSubscriptionEvent.InputTuple,
      DCAAccountSubscriptionEvent.OutputTuple,
      DCAAccountSubscriptionEvent.OutputObject
    >;
    DCAAccountSubscription: TypedContractEvent<
      DCAAccountSubscriptionEvent.InputTuple,
      DCAAccountSubscriptionEvent.OutputTuple,
      DCAAccountSubscriptionEvent.OutputObject
    >;

    "ExecutedDCA(address,uint256)": TypedContractEvent<
      ExecutedDCAEvent.InputTuple,
      ExecutedDCAEvent.OutputTuple,
      ExecutedDCAEvent.OutputObject
    >;
    ExecutedDCA: TypedContractEvent<
      ExecutedDCAEvent.InputTuple,
      ExecutedDCAEvent.OutputTuple,
      ExecutedDCAEvent.OutputObject
    >;

    "ExecutionEOAAddressChange(address,address)": TypedContractEvent<
      ExecutionEOAAddressChangeEvent.InputTuple,
      ExecutionEOAAddressChangeEvent.OutputTuple,
      ExecutionEOAAddressChangeEvent.OutputObject
    >;
    ExecutionEOAAddressChange: TypedContractEvent<
      ExecutionEOAAddressChangeEvent.InputTuple,
      ExecutionEOAAddressChangeEvent.OutputTuple,
      ExecutionEOAAddressChangeEvent.OutputObject
    >;

    "FeesDistributed(address,uint256)": TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;
    FeesDistributed: TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
