/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSwapRouter2Sol from "./ISwapRouter2.sol";
export type { iSwapRouter2Sol };
export type { IUniversalRouter } from "./IUniversalRouter";
